integrate into deploy

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -16,3 +16,19 @@ jobs:
 
       - name: Build Docker images
         run: docker compose -f deploy/production/docker-compose.production.yml build
+
+      - name: Run Unit Tests
+        run: |
+          docker compose -f deploy/production/docker-compose.production.yml up --exit-code-from unit-test
+        continue-on-error: true  # Allow the workflow to continue even if tests fail
+
+      - name: Check if Unit Tests Passed
+        id: check-tests
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Unit tests failed, stopping the workflow."
+            exit 1  # Fail the workflow if tests fail
+          fi
+
+      - name: Check running containers
+        run: docker ps
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,6 +17,19 @@ jobs:
       run: |
         docker compose -f deploy/production/docker-compose.production.yml down
 
+    - name: Run Unit Tests
+      run: |
+        docker compose -f deploy/production/docker-compose.production.yml up --exit-code-from unit-test
+      continue-on-error: true  # Allow the workflow to proceed even if this step fails
+
+    - name: Check if Unit Tests Passed
+      id: check-tests
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Unit tests failed, stopping the workflow."
+          exit 1  # Fail the workflow if tests fail
+        fi
+
     - name: Build and start Docker containers
       run: |
         docker compose -f deploy/production/docker-compose.production.yml up --build -d
